<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="19" total="20" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1797" started-at="2021-07-31T07:48:08Z" finished-at="2021-07-31T07:48:10Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1797" started-at="2021-07-31T07:48:08Z" finished-at="2021-07-31T07:48:10Z">
      <class name="com.testcases.DownloadTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.testcases.DownloadTest@31ef45e3]" name="setup" is-config="true" duration-ms="3821" started-at="2021-07-31T13:18:05Z" finished-at="2021-07-31T13:18:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="verifyVendorAndVersionFor_32bit()[pri:21, instance:com.testcases.DownloadTest@31ef45e3]" name="verifyVendorAndVersionFor_32bit" duration-ms="1779" started-at="2021-07-31T13:18:09Z" finished-at="2021-07-31T13:18:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.testcases.DownloadTest.verifyVendorAndVersionFor_32bit(DownloadTest.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyVendorAndVersionFor_32bit -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.testcases.DownloadTest@31ef45e3]" name="tearDown" is-config="true" duration-ms="657" started-at="2021-07-31T13:18:10Z" finished-at="2021-07-31T13:18:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.testcases.DownloadTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
